#全局端口定义server:
# 全局字符集设置
spring:
  aop:
    proxy-target-class: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      force: true
      enabled: true
      charset: utf-8



